### ISSUE TITLE
onError handler missing

### ISSUE THREAD

**Issue by eisisig** [enquirer/prompt-list#1]
I was trying to use this prompt when I saw that error handling was not right. As in if there is a validation on the question and it returns "an error" you could still hit enter and it would terminate the process...

After looking at the source there seems to be an onError handler missing

**Comment by jonschlinkert** [comment]
Good catch, would you like to do a pr? Or we can get it fixed asap. Thanks for reporting

**Comment by doowb** [comment]
@eisisig there is an `onError` method inherited from `prompt-base`, however the `onSubmit` method is overridden in this library and just returns when a falsey value is returned from the `validate` method.

I think we should put a `try-catch` in `prompt-base` in the `validate` method and call `onError` when there's an actual error caught. In here, we can update how invalid selections are handled and possibly render a message.

**Comment by doowb** [comment]
@eisisig this has been refactored here. If you're still running into an issue, feel free to open a new issue here or on [prompt-base](https://github.com/enquirer/prompt-base) if it applies there.
